### ISSUE TITLE
bundle/reload before TS compile

### ISSUE THREAD

**Issue by valen214** [sveltejs/template#154] opened 2020-08-02 12:51 UTC
as title
![as title](https://i.imgur.com/OKB8deF.gif)

repo: https://github.com/valen214/ts-lag-one-cycle

modification after fork:
ran `node scripts/setupTypeScript.js`
added `import { getText } from "./Foo"; console.log(getText());` to `App.svelte`
added `Foo.ts`
nothing else

**Comment by benmccann** [comment] 2020-08-02 12:57
This should probably be filed in https://github.com/sveltejs/language-tools (assuming it's an issue with the VS Code plugin and not the template)

**Comment by valen214** [comment] 2020-08-02 13:39
The problem is unrelated to VS Code.
The gif just shows edit -> save -> edit -> save -> edit -> save

**Comment by benmccann** [comment] 2020-08-02 13:43
Can you explain what's happening that's wrong compared to what you would expect to have happen?

**Comment by valen214** [comment] 2020-08-02 13:50
The code should update after it's saved,

what happens now is like:
source ============ browser
"HI"     ============== "HI"
edit source
"HI 1st edit" ======== "HI"
save                                   browser does reload
"HI 1st edit" ======== "HI"
edit source
"2nd edit" ========== "HI"
save                                 browser does reload, but seems old code is used
"2nd edit" ========= "HI 1st edit"
edit source
"3rd edit" ========= "HI 1st edit"
save                                 browser does reload
"3rd edit" ========= "2nd edit"

**Comment by benmccann** [comment] 2020-08-03 02:03
Ok. This sounds like an issue with [rollup-plugin-livereload](https://github.com/thgh/rollup-plugin-livereload) then. If it's able to be reproduced and fixed there we could upgrade the template to use any new version. But it's probably best to submit this issue there first so that the author is aware and can investigate

**Comment by valen214** [comment] 2020-08-03 04:57
I failed to confirm which but I know the problem will be fixed after updating certain dependencies

**Comment by benmccann** [comment] 2020-08-03 05:02
Ok. I'll go ahead and close this since it sounds like it was just an issue of outdated dependencies. I sent a PR to make sure the template uses the latest version of all dependencies

**Closed by benmccann** 2020-08-03 05:02 UTC

**Comment by valen214** [comment] 2020-08-03 05:06
I can confirm it's `@rollup/plugin-typescript` `4.1.2` => `5.0.2` fixes the problem.
