### ISSUE TITLE
I have problem executing: "npm run dev" in windows 10

### ISSUE THREAD

**Issue by henrycz** [sveltejs/template#197] opened 2020-12-02 16:58 UTC
I'm getting started in svelte, already installed node.js, and VScode (editor).
when I run "npm run dev" I get the following error: "Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)" and to the following reglon: "src \ App.css (1:13 ) "

"1: main.svelte-1tky8bj {text-align: center; padding: 1em; max-width: 240px; margin: 0 auto} h1.svelte-1tky8bj {color: # ff3e00; text-transform: uppercase; font-size : 4em; font-weight: 100} @media (min-width: 640px) {main.svelte-1tky8bj {max-width: none}} " please help me !!!
![errorfinal](https://user-images.githubusercontent.com/9146561/100904912-815c1880-3495-11eb-8fcb-0c60ff4568d8.png)

**Comment by Conduitry** [comment] 2020-12-02 17:12
Duplicate of #193, which I wasn't and am still not able to reproduce.

**Closed by Conduitry** 2020-12-02 17:12 UTC
