### ISSUE TITLE
Svelte await blocks cause breaking errors in Terser's compression step

### ISSUE THREAD

**Issue by igneosaur** [sveltejs/template#59] opened 2019-08-30 21:06 UTC
## Problem?

Terser is doing its thing for production builds. It carries out a second compression on _bundle.js_ that results in a breaking JS error if any Svelte files contain [`{#await ...}`](https://svelte.dev/docs#await) blocks.

## Recreate the bug

1. Add a[ Svelte file](https://github.com/igneosaur/sveltejs-template/commit/9edf388c31d8de11e9c1f47e5aacec530dc5bd2a) with an _await_ block into your application
2. Run a production build `npm run build`
3. Serve up  the _public_ directory
4. Observe dead site

<img width="596" alt="Screenshot 2019-08-30 at 17 18 17" src="https://user-images.githubusercontent.com/781658/64051961-cc8dca00-cb74-11e9-81b7-9f43fffb66f5.png">

## Fix

Since the second pass of compression on _bundle.js_ is superfluous and causes a bug, it should be removed from the Terser plugin's build step. #58

**Comment by frederikhors** [comment] 2019-08-30 23:01
It works good the await for me with default `terser()` call.

Can you push a reproduction on github?

**Comment by frederikhors** [comment] 2019-08-30 23:08
I saw the repo. I'm trying to understand the problem.

**Comment by frederikhors** [comment] 2019-08-30 23:29
I found the problem: is not terser.

**Comment by frederikhors** [comment] 2019-08-30 23:38
The problem is with `sveltejs: 3.9.1`.

With `sveltejs: 3.9.0` it works fine!

We should open an issue.

**Comment by frederikhors** [comment] 2019-08-30 23:42
Opened: https://github.com/sveltejs/svelte/issues/3483.

Please do not remove your fork, @igneosaur. Thanks.

**Comment by Conduitry** [comment] 2019-08-31 00:20
Closing this in favor of [this issue](https://github.com/sveltejs/svelte/issues/3483), which perhaps can be used to try to narrow down a repro to open against Terser.

**Closed by Conduitry** 2019-08-31 00:20 UTC
