### ISSUE TITLE
(svelte-typescript) main.ts: sourcemaps not working

### ISSUE THREAD

**Issue by goodmite** [sveltejs/template#157] opened 2020-08-03 14:42 UTC
Steps to reproduce.
1. Run following commands to create a fresh svelte ts project:
```
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```
2. Write a console statement in src/main.ts as follows:
```
import App from './App.svelte';

console.log('MAIN.TS'); //<============
const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

export default app;
```
3. Go to chrome console and click on the line number

Expectated results:: You should be taken to main.ts file in chrome instector
Actual results::         You are be taken to below file in chrome instector

![image](https://user-images.githubusercontent.com/16303528/89194742-6223ac00-d5c5-11ea-8aff-bdb3cb6327cd.png)
---------------------------
package.json
```
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public",
    "validate": "svelte-check"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^12.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^5.1.2",
    "svelte": "^3.0.0",
    "svelte-check": "^1.0.0",
    "svelte-preprocess": "^4.0.0",
    "@rollup/plugin-typescript": "^4.0.0",
    "typescript": "^3.9.3",
    "tslib": "^2.0.0",
    "@tsconfig/svelte": "^1.0.0"
  },
  "dependencies": {
    "sirv-cli": "^1.0.0"
  }
}

```

chrome:
```
Version 84.0.4147.105 (Official Build) (64-bit)
```

Windows 10

**Comment by dummdidumm** [comment] 2020-08-03 14:47
Duplicate of #145

**Comment by goodmite** [comment] 2020-08-03 14:50
Thanks @dummdidumm. Its a duplicate. 
Is there any workaround this?  I want to rewrite one of my project in svelte but can't start because of this issue as it would make debugging a big problem.
Would be really grateful if you could provide any help.

**Comment by dummdidumm** [comment] 2020-09-08 07:17
Closing in favor of #145

**Closed** 2020-09-08 07:17 UTC
