### ISSUE TITLE
using await blocks in production lead to variable being used before initialization

### ISSUE THREAD

**Issue by cryptofool13** [sveltejs/template#81] opened 2019-10-29 20:14 UTC
using the await block example from Svelte's docs leads to a ReferenceError.
## expected behavior
page loads and await block renders content after promise fulfills

## steps to reproduce
clone this repo using degit
copy code from App.svelte from [await block example](https://svelte.dev/examples#await-blocks)
and paste into App.svelte for new project.
after running
<pre>npm run build</pre> and <pre>npm run start</pre>
and navigating to localhost:5000 no content is rendered on the screen and the console displays the error: 
<pre>index.mjs:528 Uncaught ReferenceError: Cannot access 'n' before initialization
    at index.mjs:528
    at N (index.mjs:945)
    at q (App.svelte:27)
    at L (index.mjs:1287)
    at new target (main.js:3)
    at main.js:3
    at main.js:6</pre>

**Comment by Conduitry** [comment] 2019-10-29 20:34
I can't reproduce this. What version of `terser` do you have installed? (`npm ls terser`) It had a bug with the code that Svelte was generating for await blocks - https://github.com/sveltejs/svelte/issues/3483 / https://github.com/terser/terser/issues/443 - which was fixed in `terser@4.3.2`.

(As a side note, the await example won't quite work as-is in this template anyway, as it fetches from an endpoint that doesn't exist.)

**Comment by cryptofool13** [comment] 2019-10-29 21:07
Looks like it is terser@3.17.0  
My bad for using that example without noticing the invalid api call. The code in question lives in my repo [xkcd-viewer-svelte](https://github.com/cryptofool13/xkcd-viewer-svelte)

**Comment by Conduitry** [comment] 2019-10-29 21:46
The bad API call wouldn't be causing that error message (and it looks like that wouldn't be a problem in your repo anyway, as you're using a different endpoint) - but using an older version of Terser with that bug certainly could.

**Closed by Conduitry** 2019-10-29 21:46 UTC

**Comment by cryptofool13** [comment] 2019-10-29 22:23
everything works as expected now, Thanks a ton

**Comment by sw-yx** [comment] 2019-12-30 15:56
just chiming in for anyone with this `Cannot access 'n' before initialization` issue - my template had an old rollup-plugin-terser as of v4, you need to upgrade to v5.x to get that bump to terser v 4.3.2

**Comment by mrismail91** [comment] 2020-03-14 11:27
I'm still having the same issue. Heres my code.

"rollup-plugin-terser": {
      "version": "5.3.0",
      "resolved": "https://registry.npmjs.org/rollup-plugin-terser/-/rollup-plugin-terser-5.3.0.tgz",
      "integrity": "sha512-XGMJihTIO3eIBsVGq7jiNYOdDMb3pVxuzY0uhOE/FM4x/u9nQgr3+McsjzqBn3QfHIpNSZmFnpoKAwHBEcsT7g==",
      "dev": true,
      "requires": {
        "@babel/code-frame": "^7.5.5",
        "jest-worker": "^24.9.0",
        "rollup-pluginutils": "^2.8.2",
        "serialize-javascript": "^2.1.2",
        "terser": "^4.6.2"
      }
