### ISSUE TITLE
CSS in public seems to be obliterated when live reloading does its thing

### ISSUE THREAD

**Issue by JohnnyLaRue** [sveltejs/template#108] opened 2020-01-23 04:48 UTC
I'm evaluating Svelte for an upcoming project and in simply playing around with an application I downloaded via the REPL I have noticed an extremely annoying behavior when live reloading in dev mode. 

I want my CSS to live in CSS files both because I don't want Svelte touching my selectors (see https://github.com/sveltejs/svelte/issues/3104) and because the notion of single file components is incompatible with the way my cross-functional team implements and maintains style guides. 

If I make changes to `/public/global.css` and save them then these changes are reflected in the browser window exactly as expected.

If I then make any change to my actual component `.svelte` file, *everything* in `/public/global.css` seems to completely disappear until I go make a nonsense change there and save it again. Manually refreshing the page does not do anything to help. This is extremely annoying and makes development rather tedious. 

As I am a newcomer to both Svelte and Rollup, I am uncertain as to whether this is something to be expected with the default config coming out of the REPL's download button, a genuine bug, or merely an "opinion" being expressed by the framework. It's perfectly fine if it is, I just need to know so I can make a call as to whether or not we can work with Svelte.

**Comment by Conduitry** [comment] 2020-01-23 05:46
Transferring this from the svelte repo to the template repo.

That said, I can't reproduce this.

**Comment by chapmanjacobd** [comment] 2020-02-19 05:41
this is how it is supposed to work right? `/public` or `/dist` is usually a temporary directory. if you want to source a CSS file then it should be stored in `/src` or another folder

I'm not 100% sure about svelte but this is how it works in other hot-reload situations

**Comment by Conduitry** [comment] 2020-02-23 23:22
`public/build/bundle.css` is where the bundled CSS from all of the Svelte components goes. `public/global.css` should be entirely untouched by the build process, and, as far as I can tell, it is.

**Comment by Conduitry** [comment] 2020-03-18 07:34
Closing due to inactivity.

**Closed** 2020-03-18 07:34 UTC
Labels: question

**Comment by JohnnyLaRue** [comment] 2020-04-20 22:58
> Closing due to inactivity.

The development cadence of the project led us to surmise that a similar statement would be appearing on the repository's front page in the not too distant future. It's a really interesting idea and I hope someone with more resources explores it further some day.

**Comment by Conduitry** [comment] 2020-04-20 23:00
> The development cadence of the project led us to surmise that a similar statement would be appearing on the repository's front page in the not too distant future.

tee fucking hee

**Comment by AnatoleLucet** [comment] 2020-09-27 10:50
This issue happened to me yesterday. Strangely after a good night of sleep the issue disappeared...
Yesterday, I've tried to restart my linux vm but it didn't fix it. So, if you have this issue you may try to fully restart your computer (yes, it sounds like something that a novice would say). There's probably a cleaner way to fix this, meh it worked.
